# Generated by Django 3.1.2 on 2020-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogramm',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='training.Exercise', verbose_name='Упражнения'),
        ),
    ]
