# Generated by Django 3.1.2 on 2020-11-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('training', '0005_auto_20201014_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('duration', models.CharField(max_length=10, verbose_name='Время тренировки в минутах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingprogramm', verbose_name='Программа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('WARM_UP', 'Разминка'), ('EASY', 'Легко'), ('OK', 'Нормально'), ('HEAVY', 'Тяжело')], max_length=7, null=True, verbose_name='Статус')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес')),
                ('reps', models.PositiveIntegerField(default=0, verbose_name='Количество повторений')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise', verbose_name='Упражнение')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='Тренировка')),
            ],
        ),
    ]
