# Generated by Django 3.1.2 on 2020-12-08 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_auto_20201109_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingProgramm',
            new_name='TrainingProgram',
        ),
    ]
