# Generated by Django 3.1.4 on 2020-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20201208_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='image',
            field=models.ImageField(default=1, upload_to='static/upload/images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
