# Generated by Django 3.1.4 on 2020-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_trainingprogram_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='image',
            field=models.ImageField(default='static/images/200.png', upload_to='static/upload/images', verbose_name='Изображение'),
        ),
    ]
